---
title: "Hastings boats"
output: html_document
---

<style>
    body .main-container {
        max-width: 1000px;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, echo = FALSE)

# packages
library(ggplot2)
library(janitor)
library(ggplot2)
library(knitr)

# cleaned boat data
#boats_clean <- readr::read_rds("output/boats_clean.rds")

# inspect data
#dplyr::glimpse(boats_clean)
```

# Summary tables

## Still on Stade and still fishing

```{r}
boats_clean %>% janitor::tabyl(still_fishing) %>% 
  knitr::kable()
```

```{r}
boats_still_fishing <- boats_clean %>% dplyr::filter(still_fishing == "Still fishing") %>% 
  dplyr::select(
    reg_full, boat_name, date_built, location_built, weight_tons, length_m,
    -date_sig, -date_in, -date_out, -reg_number, -reg_port
  ) %>% 
  dplyr::arrange(boat_name)

boats_still_fishing %>% knitr::kable()
```



```{r}
boats_clean %>%
  janitor::tabyl(still_on_stade) %>% 
  knitr::kable()
```

```{r}
boats_on_stade <- boats_clean %>% dplyr::filter(still_on_stade == "On Stade") %>% 
  dplyr::select(
    reg_full, boat_name, date_built, location_built, weight_tons, length_m
    -date_sig, -date_in, -date_out, -reg_number, -reg_port
  ) %>% 
  dplyr::arrange(boat_name)

boats_on_stade %>% knitr::kable()
```


## Registration port

```{r}
reg_port_count <- boats_clean %>% janitor::tabyl(reg_port) %>% 
  dplyr::arrange(desc(n)) %>% 
  dplyr::left_join(
    y = dplyr::distinct(dplyr::select(boats_clean, reg_port, reg_port_name)),
    by = "reg_port"
  ) %>% 
  dplyr::select(reg_port, reg_port_name, dplyr::everything())

reg_port_count %>% knitr::kable()
```


```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_bar(aes(x = reg_port))
```


## Propulsion

```{r}
boats_clean %>% janitor::tabyl(propulsion) %>% 
  dplyr::arrange(desc(n)) %>% 
  knitr::kable()
```

```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_bar(aes(x = propulsion)) +
  coord_flip()
```

## Construction material

```{r}
boats_clean %>% janitor::tabyl(construction_material) %>% 
  dplyr::arrange(desc(n)) %>% 
  knitr::kable()
```

```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_bar(aes(x = construction_material)) +
  coord_flip()
```

## Deck type

```{r}
boats_clean %>% janitor::tabyl(deck_type) %>% 
  dplyr::arrange(desc(n)) %>% 
  knitr::kable()
```

```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_bar(aes(x = deck_type)) +
  coord_flip()
```

## Length

```{r}
boats_clean %>%
  dplyr::arrange(desc(length_m)) %>% 
  dplyr::select(reg_full, boat_name, length_m) %>% 
  dplyr::filter(length_m > 10) %>% 
  knitr::kable()
```

```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_histogram(aes(x = length_m))
```

## Weight

```{r}
boats_clean %>%
  dplyr::arrange(desc(weight_tons)) %>% 
  dplyr::select(reg_full, boat_name, weight_tons) %>% 
  dplyr::filter(weight_tons > 25) %>% 
  knitr::kable()
```

```{r}
boats_clean %>%
  ggplot2::ggplot() + 
  geom_histogram(aes(x = weight_tons))